In [34]:
import numpy as np

In [35]:
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [39]:
n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

# Initializing numpy array with zeros

In [43]:
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [47]:
n2=np.zeros((5,5),dtype=int)
n2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Initializing numpy array with same number

In [50]:
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

# Initializing numpy array with a range

In [52]:
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
n2=np.arange(10,50,5)
#5 means skip value --> press shift+tab

In [54]:
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

# Initializing numpy array with Random number

In [58]:
n1=np.random.randint(1,100,5)
# 5 means how many numbers do we need

In [59]:
n1

array([59, 90, 76, 50, 87])

# Numpy Shape

In [60]:
n1=np.array([[1,2,3],[4,5,6]])

In [61]:
n1.shape

(2L, 3L)

In [63]:
n1.shape=(3,2)
#changing shape value

In [64]:
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

# Joining Numpy Array

In [65]:
n1=np.array([10,20,30,40])
n2=np.array([50,60,70,80])

In [66]:
np.vstack((n1,n2))
# v for vertical

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [68]:
np.hstack((n1,n2))
# h for horizontal

array([10, 20, 30, 40, 50, 60, 70, 80])

In [69]:
np.column_stack((n1,n2))
# kind of transpose

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

# Numpy Intersection & Difference

In [70]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

In [71]:
np.intersect1d(n1,n2)

array([50, 60])

In [72]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [73]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

# Addition of Numpy Arrays

In [74]:
n1=np.array([10,20])
n2=np.array([30,40])

In [75]:
np.sum([n1,n2])

100

In [76]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [77]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [78]:
np.mean(n1)

15.0

In [79]:
np.median(n1)

15.0

In [80]:
np.std(n1)

5.0